# Generated by Django 4.0 on 2022-01-11 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('card_type', models.CharField(choices=[('C', 'City Center'), ('S', 'Small Town')], max_length=1)),
                ('employee_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('funds', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transaction_date', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('T', 'Top-Up'), ('P', 'Purchase'), ('R', 'Refund')], max_length=1)),
                ('restaurant', models.CharField(max_length=255, null=True)),
                ('card_id', models.ForeignKey(default='company', on_delete=django.db.models.deletion.SET_DEFAULT, to='monthly.card')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monthly.company')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monthly.company'),
        ),
    ]
