# Generated by Django 4.0 on 2022-01-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly', '0002_rename_company_id_card_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='restaurant',
            new_name='transaction_name',
        ),
    ]
