# Generated by Django 4.0 on 2022-01-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly', '0003_rename_restaurant_transaction_transaction_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['employee_name']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name']},
        ),
        migrations.AlterField(
            model_name='card',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
