# Generated by Django 4.0 on 2022-01-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monthly', '0004_alter_card_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['company']},
        ),
        migrations.AlterField(
            model_name='company',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monthly.company'), on_delete=django.db.models.deletion.SET_DEFAULT, to='monthly.card'),
        ),
    ]
